### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by divyajomi08** [divyajomi08/neeto-ui-challenge-divya-jomi#8]

**Comment by divyajomi08** [comment]
Deployed at [https://neeto-ui-challenge-divya.neetoreviewapp.net](https://neeto-ui-challenge-divya.neetoreviewapp.net)

Login credentials:
Username: oliver@example.com
Password: welcome

@yedhink  @navaneethsdk  Please review

**Comment by navaneethsdk** [comment]
@divyajomi08 a few comments
- [ ] Let's make sure that the title has at least one alphanumeric value:
https://github.com/divyajomi08/neeto-ui-challenge-divya-jomi/blob/a0135b41d256dff36124a161c0462b0fa43ca39d/app/javascript/src/components/Dashboard/Notes/Pane/Form/constants.js#L5
- [ ] Let's move this to a separate utils function prefixed with `render` keyword. [Refer](https://academy.bigbinary.com/learn-react/react-best-practices/naming-conventions-in-react#when-to-use-the-render-keyword): https://github.com/divyajomi08/neeto-ui-challenge-divya-jomi/blob/a0135b41d256dff36124a161c0462b0fa43ca39d/app/javascript/src/components/Dashboard/Contacts/Table/utils.jsx#L19-L40 https://github.com/divyajomi08/neeto-ui-challenge-divya-jomi/blob/a0135b41d256dff36124a161c0462b0fa43ca39d/app/javascript/src/components/Dashboard/Contacts/Table/utils.jsx#L54-L63

Rest of the application LGTM. Nice work on incorporating RamdaJS.

**Comment by yedhink** [comment]
@divyajomi08 LGTM. Once the above mentioned issues are fixed, you can close this issue.
